baseURL: "https://cesarcma.github.io/cesarcma_site/"
publishDir: "public"
languageCode: "en-us"
title: "CesarCMa"
theme: hugo-profile-mod

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "CesarCMa"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo.svg" 

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  color:
    textColor: "#575279"
    secondaryTextColor: "#797593"
    textLinkColor: "#b4637a"
    backgroundColor: "#faf4ed"
    secondaryBackgroundColor: "#f2e9e1"
    primaryColor: "#286983"
    secondaryColor: "#f2e9e1"

    darkmode:
      textColor: "#e0def4"
      secondaryTextColor: "#908caa"
      textLinkColor: "#eb6f92"
      backgroundColor: "#232136"
      secondaryBackgroundColor: "#2a273f"
      primaryColor: "#3e8fb0"
      secondaryColor: "#393552"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "CesarCMa" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi 👋, my name is"
    title: "César Capilla"
    subtitle: "I'm a Machine Learning Engineer."
    content: "I like to build software tools that leverage data to solve **real** problems."
    image: /images/portrait.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#" # TODO: add url to download pdf with CV
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/CesarCMa
        - icon: fab fa-x-twitter
          url: https://x.com/sekinox
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/cesarcapillama/

  # About
  about:
    enable: true
    title: "About Me"
    image: ""
    content: |-
      Mathematician and passionate about programming and tech since childhood. I began my professional career as a data scientist and have recently made a career shift, focusing on backend development and cloud infrastructure for Machine Learning systems.

      My main motivations are learning new things, solving problems and creating value.
    skills:
      enable: true
      title: "These are the technologies/frameworks I use on a daily basis:"
      items:
        - "Python"
        - "MLOps"
        - "AWS Cloud"
        - "Docker"
        - "SQL"
        - "Git"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    companies:
      - name: "Novartis"
        url: "https://www.novartis.com/"
        jobs:
          - position: "Software Developer / ML Engineer"
            date: "Oct 2021- Present"
            featuredLink:
              enable: false
            content: |
              I am currently working as a Machine Learning Engineer on the Digital Finance Hub in Barcelona. My main responsibilities are:

              - Refactor and deploy on cloud PoC projects developed by Data Scientist
              
              - Implement MLOps processes that ensure the robustness and scalability of our machine learning models

              - Mentoring new team members

          - position: "Expert in Data Science"
            date: "Oct 2021- Sep 2024"
            featuredLink:
              enable: false
            content: |
              - Drive the implementation of MLOps processes on a specific project, automating the evaluation of models and developing dashboards that enable easy tracking of new model versions.

              - Product Owner within the Digital Finance Hub in a sales forecasting project, leading the latest phase of the project involving scope expansion of the forecasting model and moving it into maintenance.

              - Collaboration with Novartis Technical Operations acting as Data Scientist in a cost forecasting project, developing the main model during PoC phase and leading expansion of the project to new plants.

              - Conduct technical sessions to get to know work developed within the Digital Finance Hub to non-technical profiles both inside and outside Novartis

      - name: "ConnecThink Innovation"
        url: "https://connecthink.ai/inicio"
        jobs:
          - position: "Data Scientist"
            date: "March 2020 - Sep 2021"
            featuredLink:
              enable: false
            content: |
              - Social media data mining via natural language processing and graph databases.

              - Automation of warranty processing via machine learning models, using Dataiku as main workframe.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master's in Artificial Intelligence"
        school:
          name: "Universitat de València"
          url: "https://postgrado.adeituv.es/es/cursos/area_de_ciencias_y_tecnologia-8/inteligencia-artificial-IA/datos_generales.htm"
        date: "2023 - Present"
        content: |-
          Master's Degree focused on:
          - Classical deep learning models such as CNN, NN or LSTM
          - Reinforcement Learning models
          - Natural language processing models, including the latest technologies such as LLMs and RAG.
          - Cloud AI environments
          - Industrialization of AI products
      - title: "Bachelor's Degree in Mathematical Sciences"
        school:
          name: "Universitat de València"
          url: "https://www.uv.es/uvweb/universitat/ca/estudis-grau/oferta-graus/oferta-graus/grau-matematiques-1285846094474/Titulacio.html?id=1285847387296"
        date: "2015-2021"
        content: ""

  # projects
  projects:
    enable: true
    title: "Side Projects"
    items:
      - title: Personal Website
        content: This beatiful website you are visiting right now.
        image: /images/projects/personal_site.png
        badges:
          - "Hugo"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/CesarCMa/cesarcma_site

      - title: Recurrent Homer
        content: A simple text generator based on recurrent neural networks. Done during the course of Master's Degree in Artificial Intelligence at the Universitat de València.
        image: /images/projects/recurrent_homer.png
        badges:
          - "Python"
          - "TensorFlow"
          - "Streamlit"
        links:
          - icon: fab fa-github
            url: https://github.com/CesarCMa/recurrent_homer

      - title: Mortgage Calculator
        content: A CLI tool to calculate the monthly payment of a mortgage. Done to put in practice C programming language after completing C-from zero to hero course on LowLeveAcademy.
        image: /images/projects/mort_calc.png
        badges:
          - "C"
        links:
          - icon: fab fa-github
            url: https://github.com/CesarCMa/mort_calc

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Do you have any questions or just want to say hi? Don't hesitate to reach out! 
    btnName: Mail me
    mailto: cesar.capilla97@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: true

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: true

  # Single pages like blog and post
  singlePages:
    socialShare: false
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
